/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AiProviderStatusProvider = typeof AiProviderStatusProvider[keyof typeof AiProviderStatusProvider];
export declare const AiProviderStatusProvider: {
    readonly Anthropic: "Anthropic";
    readonly OpenAI: "OpenAI";
};
//# sourceMappingURL=aiProviderStatusProvider.d.ts.map