/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AiProviderStatusCreditStatus = typeof AiProviderStatusCreditStatus[keyof typeof AiProviderStatusCreditStatus];
export declare const AiProviderStatusCreditStatus: {
    readonly available: "available";
    readonly exhausted: "exhausted";
    readonly unknown: "unknown";
};
//# sourceMappingURL=aiProviderStatusCreditStatus.d.ts.map