/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AgentCostEstimate } from './agentCostEstimate';
import type { AiProviderStatusCostEstimateBasis } from './aiProviderStatusCostEstimateBasis';
import type { AiProviderStatusCostEstimateTotal } from './aiProviderStatusCostEstimateTotal';
export type AiProviderStatusCostEstimate = {
    basis: AiProviderStatusCostEstimateBasis;
    disclaimer: string;
    interpret: AgentCostEstimate;
    verifier: AgentCostEstimate;
    total: AiProviderStatusCostEstimateTotal;
};
//# sourceMappingURL=aiProviderStatusCostEstimate.d.ts.map