/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AiProviderStatusState = typeof AiProviderStatusState[keyof typeof AiProviderStatusState];
export declare const AiProviderStatusState: {
    readonly ready: "ready";
    readonly blocked: "blocked";
    readonly degraded: "degraded";
    readonly unknown: "unknown";
    readonly not_configured: "not_configured";
};
//# sourceMappingURL=aiProviderStatusState.d.ts.map