/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AiProviderStatusCostEstimateBasis = typeof AiProviderStatusCostEstimateBasis[keyof typeof AiProviderStatusCostEstimateBasis];
export declare const AiProviderStatusCostEstimateBasis: {
    readonly historical: "historical";
    readonly default: "default";
};
//# sourceMappingURL=aiProviderStatusCostEstimateBasis.d.ts.map