/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type AnalysisProgressPhase = typeof AnalysisProgressPhase[keyof typeof AnalysisProgressPhase] | null;
export declare const AnalysisProgressPhase: {
    readonly preparation: "preparation";
    readonly technical: "technical";
    readonly evidence: "evidence";
    readonly interpret: "interpret";
    readonly verifier: "verifier";
    readonly finalization: "finalization";
};
//# sourceMappingURL=analysisProgressPhase.d.ts.map