/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AnalysisMediaType = typeof AnalysisMediaType[keyof typeof AnalysisMediaType];
export declare const AnalysisMediaType: {
    readonly video: "video";
    readonly image: "image";
};
//# sourceMappingURL=analysisMediaType.d.ts.map