/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type AnalysisManualVerdict = typeof AnalysisManualVerdict[keyof typeof AnalysisManualVerdict] | null;
export declare const AnalysisManualVerdict: {
    readonly ORIGINAL: "ORIGINAL";
    readonly UPRAVENO: "UPRAVENO";
    readonly UPRAVENO_AI: "UPRAVENO_AI";
    readonly CELE_AI: "CELE_AI";
    readonly NEJISTE: "NEJISTE";
};
//# sourceMappingURL=analysisManualVerdict.d.ts.map