/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AnalysisStatus = typeof AnalysisStatus[keyof typeof AnalysisStatus];
export declare const AnalysisStatus: {
    readonly queued: "queued";
    readonly analyzing: "analyzing";
    readonly complete: "complete";
    readonly failed: "failed";
};
//# sourceMappingURL=analysisStatus.d.ts.map