/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AnalysisVerdict = typeof AnalysisVerdict[keyof typeof AnalysisVerdict];
export declare const AnalysisVerdict: {
    readonly ORIGINÁL: "ORIGINÁL";
    readonly UPRAVENO: "UPRAVENO";
    readonly UPRAVENO_AI: "UPRAVENO_AI";
    readonly CELE_AI: "CELE_AI";
    readonly NEURČENO: "NEURČENO";
};
//# sourceMappingURL=analysisVerdict.d.ts.map