/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type AnalysisFinalStatus = typeof AnalysisFinalStatus[keyof typeof AnalysisFinalStatus] | null;
export declare const AnalysisFinalStatus: {
    readonly POTVRZENO: "POTVRZENO";
    readonly SPORNE: "SPORNE";
    readonly NEJISTE: "NEJISTE";
    readonly CHYBA_API: "CHYBA_API";
};
//# sourceMappingURL=analysisFinalStatus.d.ts.map