/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisAiUsage } from './analysisAiUsage';
import type { AnalysisFinalStatus } from './analysisFinalStatus';
import type { AnalysisManualVerdict } from './analysisManualVerdict';
import type { AnalysisMediaType } from './analysisMediaType';
import type { AnalysisProgressPhase } from './analysisProgressPhase';
import type { AnalysisStatus } from './analysisStatus';
import type { AnalysisVerdict } from './analysisVerdict';
import type { Evidence } from './evidence';
import type { InterpretResult } from './interpretResult';
import type { MetadataSummary } from './metadataSummary';
import type { PipelineStep } from './pipelineStep';
import type { VerifierResult } from './verifierResult';
export interface Analysis {
    id: number;
    name: string;
    status: AnalysisStatus;
    verdict: AnalysisVerdict;
    /**
       * @minimum 0
       * @maximum 100
       */
    confidence: number;
    createdAt: Date;
    updatedAt: Date;
    /**
       * @minimum 0
       * @maximum 100
       */
    progressPercent: number;
    /** @nullable */
    progressPhase: AnalysisProgressPhase;
    /** @nullable */
    progressPhaseLabel: string | null;
    /** @nullable */
    analysisStartedAt: Date | null;
    /** @minimum 0 */
    elapsedSeconds: number;
    /**
       * @minimum 0
       * @nullable
       */
    etaSeconds: number | null;
    progressEstimated: boolean;
    evidenceCount: number;
    metadata: MetadataSummary;
    mediaType: AnalysisMediaType;
    pipelineSteps: PipelineStep[];
    evidence?: Evidence[];
    /** @nullable */
    objectPath?: string | null;
    /** @nullable */
    reportHtml?: string | null;
    /** @nullable */
    fileHash?: string | null;
    /** @nullable */
    finalStatus?: AnalysisFinalStatus;
    interpretResult?: InterpretResult | null;
    verifierResult?: VerifierResult | null;
    /** @nullable */
    apiError?: string | null;
    /** @nullable */
    manualVerdict?: AnalysisManualVerdict;
    estimatedCostUsd?: number;
    aiUsage: AnalysisAiUsage;
}
//# sourceMappingURL=analysis.d.ts.map