/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type AnalysisAiUsage = {
    /**
       * @minimum 0
       * @nullable
       */
    interpretInputTokens: number | null;
    /**
       * @minimum 0
       * @nullable
       */
    interpretOutputTokens: number | null;
    /**
       * @minimum 0
       * @nullable
       */
    interpretCostUsd: number | null;
    /**
       * @minimum 0
       * @nullable
       */
    verifierInputTokens: number | null;
    /**
       * @minimum 0
       * @nullable
       */
    verifierOutputTokens: number | null;
    /**
       * @minimum 0
       * @nullable
       */
    verifierCostUsd: number | null;
};
//# sourceMappingURL=analysisAiUsage.d.ts.map