/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface EditingSoftware {
    detected: boolean;
    /** @nullable */
    name: string | null;
    /**
       * tag source, tag_absent, or no_match
       * @nullable
       */
    source: string | null;
    /** @nullable */
    rawEncoder: string | null;
    /** @nullable */
    confidence: string | null;
    /** @nullable */
    evidence: string | null;
}
//# sourceMappingURL=editingSoftware.d.ts.map