/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { EvidenceSeverity } from './evidenceSeverity';
import type { ImageRegion } from './imageRegion';
export interface Evidence {
    category: string;
    title: string;
    detail: string;
    severity: EvidenceSeverity;
    /** @nullable */
    timestamp?: string | null;
    /**
       * @minimum 0
       * @nullable
       */
    timestampSeconds?: number | null;
    /**
       * @minimum 0
       * @maximum 1
       */
    score?: number;
    regions?: ImageRegion[];
}
//# sourceMappingURL=evidence.d.ts.map