/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type EvidenceSeverity = typeof EvidenceSeverity[keyof typeof EvidenceSeverity];
export declare const EvidenceSeverity: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
//# sourceMappingURL=evidenceSeverity.d.ts.map