/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface ImageRegion {
    /** @minimum 0 */
    x: number;
    /** @minimum 0 */
    y: number;
    /** @minimum 1 */
    width: number;
    /** @minimum 1 */
    height: number;
    /**
       * @minimum 0
       * @maximum 1
       */
    score: number;
    label: string;
}
//# sourceMappingURL=imageRegion.d.ts.map