/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type InterpretResultVerdict = typeof InterpretResultVerdict[keyof typeof InterpretResultVerdict];
export declare const InterpretResultVerdict: {
    readonly ORIGINAL: "ORIGINAL";
    readonly UPRAVENO: "UPRAVENO";
    readonly UPRAVENO_AI: "UPRAVENO_AI";
    readonly CELE_AI: "CELE_AI";
    readonly NEJASNE: "NEJASNE";
};
//# sourceMappingURL=interpretResultVerdict.d.ts.map