/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type ManualVerdictInputVerdict = typeof ManualVerdictInputVerdict[keyof typeof ManualVerdictInputVerdict];
export declare const ManualVerdictInputVerdict: {
    readonly ORIGINAL: "ORIGINAL";
    readonly UPRAVENO: "UPRAVENO";
    readonly UPRAVENO_AI: "UPRAVENO_AI";
    readonly CELE_AI: "CELE_AI";
    readonly NEJISTE: "NEJISTE";
};
//# sourceMappingURL=manualVerdictInputVerdict.d.ts.map