/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { EditingSoftware } from './editingSoftware';
import type { MetadataSummaryAllMetadata } from './metadataSummaryAllMetadata';
export interface MetadataSummary {
    container: string;
    codec: string;
    duration: number;
    /** @nullable */
    createdAt: string | null;
    /** @nullable */
    modifiedAt: string | null;
    /** @nullable */
    encoder: string | null;
    /** @nullable */
    bitrate?: number | null;
    /** @nullable */
    frameRate?: string | null;
    /** @nullable */
    resolution?: string | null;
    editingSoftware: EditingSoftware;
    allMetadata?: MetadataSummaryAllMetadata;
}
//# sourceMappingURL=metadataSummary.d.ts.map