/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PipelineStepResultJson } from './pipelineStepResultJson';
import type { PipelineStepStepStatus } from './pipelineStepStepStatus';
export interface PipelineStep {
    stepName: string;
    stepStatus: PipelineStepStepStatus;
    /** @nullable */
    resultJson: PipelineStepResultJson;
    /** @nullable */
    errorMessage: string | null;
}
//# sourceMappingURL=pipelineStep.d.ts.map