/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PipelineStepStepStatus = typeof PipelineStepStepStatus[keyof typeof PipelineStepStepStatus];
export declare const PipelineStepStepStatus: {
    readonly OK: "OK";
    readonly NEDOSTUPNE: "NEDOSTUPNE";
    readonly CHYBA: "CHYBA";
};
//# sourceMappingURL=pipelineStepStepStatus.d.ts.map