/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type VerifierResultFinalniStatus = typeof VerifierResultFinalniStatus[keyof typeof VerifierResultFinalniStatus];
export declare const VerifierResultFinalniStatus: {
    readonly POTVRZENO: "POTVRZENO";
    readonly SPORNE: "SPORNE";
    readonly NEJISTE: "NEJISTE";
};
//# sourceMappingURL=verifierResultFinalniStatus.d.ts.map