/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type VideoTextOverlayPosition = typeof VideoTextOverlayPosition[keyof typeof VideoTextOverlayPosition];
export declare const VideoTextOverlayPosition: {
    readonly top: "top";
    readonly center: "center";
    readonly bottom: "bottom";
};
//# sourceMappingURL=videoTextOverlayPosition.d.ts.map