/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type VideoEditClipTransition = typeof VideoEditClipTransition[keyof typeof VideoEditClipTransition];
export declare const VideoEditClipTransition: {
    readonly none: "none";
    readonly fade: "fade";
};
//# sourceMappingURL=videoEditClipTransition.d.ts.map