/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type VideoEditProjectFilter = typeof VideoEditProjectFilter[keyof typeof VideoEditProjectFilter];
export declare const VideoEditProjectFilter: {
    readonly none: "none";
    readonly grayscale: "grayscale";
    readonly warm: "warm";
    readonly cool: "cool";
    readonly contrast: "contrast";
};
//# sourceMappingURL=videoEditProjectFilter.d.ts.map